### ISSUE TITLE
Does Rerollbot work with mod?

### ISSUE THREAD

**Issue by AT231** [NiHoel/Anno1800UXEnhancer#12]
My game has modded. I used the "Unlocker trader" mod to buy legendary items. I tried to use the rerollbot but it doesn't work.
Things that  I do:
- Disable DVR
- Set the game to Window Full Screen
 Any way I can make it work? Thanks
Update1: The rerollbot seems to works in the game but it doesn't buy anything, just keep rerolling. 
- Maybe because the Trader display too many items (because of the mod) so the bot can't buy the items that not display on the first 3 rows?

**Comment by NiHoel** [comment]
If you have downloaded the latest version (v5.1), then it should buy all items regularly sold by the trader (it checks all 12 items).
You can give it a try to a add legendaries: Open assets/texts/items.json and add the new items to every trader (use the AssetViewer to look up trader and item guids). 

Make sure you add all of them the mod adds. Otherwise the following might happen: Assume you have added item a but not b. If the trader offers b, the bot think it's a and will erroneously buy it.

**Comment by AT231** [comment]
The mod I use is "[All Items Unlocked](https://www.nexusmods.com/anno1800/mods/44?tab=files&file_id=222)" . 
So the trader display over 100 items on the page (all the items in the game). Does it cause the bot doesn't buy it because the bot just checks 12 first item? Every item is there but the bot doesn't buy it.

**Comment by NiHoel** [comment]
Is it a scrollable list? The bot only checks what it can see (within the area where items are normally offered)

**Comment by AT231** [comment]
yes, it a scrollable list. So that why the bot keep reroll. Anyway to make the bot check all the list?

**Comment by NiHoel** [comment]
No, there is no easy-to-implement and safe way to check the list. Since you use mods anyway, you can restrict the offer to those items you want to buy. 

But (for me) it is not worth the extra effort to support mods.
