### ISSUE TITLE
Increase the Speed for UEXEnhancer

### ISSUE THREAD

**Issue by FaderAway** [NiHoel/Anno1800UXEnhancer#7]
Hello NiHoel,

first of all...thanks alot...its the best support tool i ever used.

Q: Is it possible to increase the speed of rerolling?!? The tutorials look like ones a second...but for me its 3-4 seconds for rerolling ones.

Thanks for help
Greetz from FarAway

**Comment by NiHoel** [comment]
The maximum speed is 4 rerolls per second.

Reasons why it is slower:

- Evaluating which items are displayed takes some time (100 ms or more, depends on CPU speed)
- Item icons are not immediately displayed (depends on drive, sometimes one can see that the icons appear delayed) -> re-evalutes icons 100 ms later
- Detection of one or more items fails permanently -> after 3 re-evaluation tries a reroll is done nevertheless

What is the shortest time you experienced between two rerolls? -> that is what your computer is capable of
Longer waiting times are due to slow loading of images -> put game onto SSD

**Comment by FaderAway** [comment]
Hiho...

my testing was on 4k. on ssd with gtx980 ...lower up performance get it to 1s reroll.
whats the best options to get it to 4 times a second??!

**Comment by NiHoel** [comment]
Have a dedicate, fast CPU kernel for UXEnhancer is the best option. 

You may try:
- Close all other applications (e.g. when recording the demo video, rerolling was slower than without recording)
- Set task priority of UXEnhancer to high in task manager

The 4 rerolls is not achievable in practice, but 2 per second is.

**Comment by FaderAway** [comment]
Working perfect with lower Performance and tweaking priority of UEXEnhancer. 
brought it up to 2-3 times a second...thats all i wanted.

Thank you for fast responding. 
Cya in the "Land of the Lions".
